DROP TABLE IF EXISTS tvodacces;
DROP TABLE IF EXISTS user_subscriptions;
DROP TABLE IF EXISTS subscriptions;
DROP TABLE IF EXISTS resource_subsription_categories;
DROP TABLE IF EXISTS subscription_categories;
DROP TABLE IF EXISTS resources_categories_m2m;
DROP TABLE IF EXISTS resources;
DROP TABLE IF EXISTS resource_categories;
DROP TYPE IF EXISTS duration;