// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.12.4
// source: resource_category.proto

package subscription_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResourceCategory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title             string      `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Key               string      `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	AllowAllResources bool        `protobuf:"varint,4,opt,name=allow_all_resources,json=allowAllResources,proto3" json:"allow_all_resources,omitempty"`
	Resources         []*Resource `protobuf:"bytes,5,rep,name=resources,proto3" json:"resources,omitempty"`
	CreatedAt         string      `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         string      `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *ResourceCategory) Reset() {
	*x = ResourceCategory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resource_category_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceCategory) ProtoMessage() {}

func (x *ResourceCategory) ProtoReflect() protoreflect.Message {
	mi := &file_resource_category_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceCategory.ProtoReflect.Descriptor instead.
func (*ResourceCategory) Descriptor() ([]byte, []int) {
	return file_resource_category_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceCategory) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResourceCategory) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ResourceCategory) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ResourceCategory) GetAllowAllResources() bool {
	if x != nil {
		return x.AllowAllResources
	}
	return false
}

func (x *ResourceCategory) GetResources() []*Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *ResourceCategory) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ResourceCategory) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ResourceCategories struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int32               `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Items []*ResourceCategory `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ResourceCategories) Reset() {
	*x = ResourceCategories{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resource_category_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceCategories) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceCategories) ProtoMessage() {}

func (x *ResourceCategories) ProtoReflect() protoreflect.Message {
	mi := &file_resource_category_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceCategories.ProtoReflect.Descriptor instead.
func (*ResourceCategories) Descriptor() ([]byte, []int) {
	return file_resource_category_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceCategories) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ResourceCategories) GetItems() []*ResourceCategory {
	if x != nil {
		return x.Items
	}
	return nil
}

type ResourceAndCategoryIds struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryId string   `protobuf:"bytes,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	ResourceId []string `protobuf:"bytes,3,rep,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
}

func (x *ResourceAndCategoryIds) Reset() {
	*x = ResourceAndCategoryIds{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resource_category_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceAndCategoryIds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceAndCategoryIds) ProtoMessage() {}

func (x *ResourceAndCategoryIds) ProtoReflect() protoreflect.Message {
	mi := &file_resource_category_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceAndCategoryIds.ProtoReflect.Descriptor instead.
func (*ResourceAndCategoryIds) Descriptor() ([]byte, []int) {
	return file_resource_category_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceAndCategoryIds) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResourceAndCategoryIds) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *ResourceAndCategoryIds) GetResourceId() []string {
	if x != nil {
		return x.ResourceId
	}
	return nil
}

var File_resource_category_proto protoreflect.FileDescriptor

var file_resource_category_proto_rawDesc = []byte{
	0x0a, 0x17, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x73, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a,
	0x0e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xf6, 0x01, 0x0a, 0x10, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2e, 0x0a, 0x13,
	0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x61, 0x6c, 0x6c, 0x5f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x61, 0x6c, 0x6c, 0x6f, 0x77,
	0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x3c, 0x0a, 0x09,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52,
	0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x68, 0x0a, 0x12, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x3c, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x05, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x22, 0x6a, 0x0a, 0x16, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x41, 0x6e,
	0x64, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x73, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b,
	0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x12, 0x1f, 0x0a,
	0x0b, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x42, 0x1f,
	0x5a, 0x1d, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_resource_category_proto_rawDescOnce sync.Once
	file_resource_category_proto_rawDescData = file_resource_category_proto_rawDesc
)

func file_resource_category_proto_rawDescGZIP() []byte {
	file_resource_category_proto_rawDescOnce.Do(func() {
		file_resource_category_proto_rawDescData = protoimpl.X.CompressGZIP(file_resource_category_proto_rawDescData)
	})
	return file_resource_category_proto_rawDescData
}

var file_resource_category_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_resource_category_proto_goTypes = []interface{}{
	(*ResourceCategory)(nil),       // 0: subscription_service.ResourceCategory
	(*ResourceCategories)(nil),     // 1: subscription_service.ResourceCategories
	(*ResourceAndCategoryIds)(nil), // 2: subscription_service.ResourceAndCategoryIds
	(*Resource)(nil),               // 3: subscription_service.Resource
}
var file_resource_category_proto_depIdxs = []int32{
	3, // 0: subscription_service.ResourceCategory.resources:type_name -> subscription_service.Resource
	0, // 1: subscription_service.ResourceCategories.items:type_name -> subscription_service.ResourceCategory
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_resource_category_proto_init() }
func file_resource_category_proto_init() {
	if File_resource_category_proto != nil {
		return
	}
	file_resource_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_resource_category_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceCategory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resource_category_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceCategories); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resource_category_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceAndCategoryIds); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_resource_category_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_resource_category_proto_goTypes,
		DependencyIndexes: file_resource_category_proto_depIdxs,
		MessageInfos:      file_resource_category_proto_msgTypes,
	}.Build()
	File_resource_category_proto = out.File
	file_resource_category_proto_rawDesc = nil
	file_resource_category_proto_goTypes = nil
	file_resource_category_proto_depIdxs = nil
}
